### ISSUE TITLE
Installation doesn't work :-( 

### ISSUE THREAD

**Issue by ldacosta** [RenfangLiao/web-crawler#1]
I did `docker build -t crawler_test .` but then I get an error
![Screenshot from 2021-09-22 15-23-13](https://user-images.githubusercontent.com/2474410/134408394-69e58c85-9a07-4c97-b010-60662ba59b78.png)
Can you help me?

**Comment by RenfangLiao** [comment]
Hey Luis, 
Sorry about the trouble. I have never seen this error before, and I could not reproduce it. Now I am trying to ask my friends to run the docker build to see if it happens on their machine. Will get back to you once I find the solution. 
![image](https://user-images.githubusercontent.com/15148647/134413003-1b721f48-4bc1-4b93-937f-e0c4fa970db7.png)

**Comment by RenfangLiao** [comment]
Hey Huis, 
I just updated the docker image tag to be a specific one. Hopefully this can address the problem. Could you give it a shot?

**Comment by sperez8** [comment]
Worked for me :)

**Comment by ldacosta** [comment]
Hi Alice. I know what's happening: my docker installation needs some love (I just changed laptops). There is some configuration problem I need to discuss with sys admin. Will let you know how it goes!
